- hosts: servers
  become: yes
  tasks:
  - name: Installer les dépendances nécessaires
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      update_cache: yes

  - name: Ajouter la clé GPG officielle de Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Ajouter le dépôt Docker
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Installer Docker et Docker Compose
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      update_cache: yes

  - name: Cloner le dépôt Git
    git:
      repo: 'https://github.com/hugo-HDSF/M1PEX_TP_EVAL_docker'
      dest: /var/www/html/M1PEX_TP_EVAL_docker

  - name: Construire et déployer avec Docker Compose
    shell: |
      cd /var/www/html/M1PEX_TP_EVAL_docker
      make build -d
    args:
      executable: /bin/bash
